# Generated by Django 4.2.2 on 2023-07-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedupeapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='completed_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dupe',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
