# Generated by Django 4.2.2 on 2023-07-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedupeapi', '0002_alter_checkoutsession_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
