# Generated by Django 4.2.2 on 2023-07-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedupeapi', '0003_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dupe',
            name='company',
            field=models.CharField(max_length=55),
        ),
    ]
