# Generated by Django 4.2.2 on 2023-07-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedupeapi', '0004_alter_dupe_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
